### ISSUE TITLE
EventHubs.Define does not create all rules

### ISSUE THREAD

**Issue by MariuszKogut** [Azure/azure-libraries-for-net#891] opened 2019-11-14 14:49 UTC
**Describe the bug**
I'm using EventHub.Define to create a new EventHub with both SendRule and ListenRule. After creating the hub I'm using eventHub.ListAuthorizationRulesAsync to get all rules. Since Monday eventHub.ListAuthorizationRulesAsync does not return the correct count of Rules. Even a retry strategy using Polly does not fix that problem.

***Exception or Stack Trace***
There is no exception. The API returns not all rules.

**To Reproduce**

***Code Snippet***
```C#
var eventHubs = await azure.EventHubNamespaces.ListByResourceGroupAsync(resourceGroupName);
var eventHubNamespace = eventHubs.FirstOrDefault(x => x.Name == eventHubNamespaceName);

if (eventHubNamespace == null)
{
	eventHubNamespace = await azure.EventHubNamespaces.Define(eventHubNamespaceName)
		.WithRegion(Region.EuropeWest)
		.WithExistingResourceGroup(resourceGroupName)
		.CreateAsync();
}

var eventHub = await azure.EventHubs.Define(eventHubName)
	.WithExistingNamespace(eventHubNamespace)
	.WithPartitionCount(1) // Use only 1 partition, to avoid that event order is destroyed. 
	.WithNewSendRule(Names.EventHubNamespace.SendRule)
	.WithNewListenRule(Names.EventHubNamespace.ListenRule)
	.CreateAsync();

// Retry 8 times because sometimes the keys are not there  
var rules = await Policy
	.Handle<InvalidOperationException>()
	.WaitAndRetryAsync(9, retryAttempt => TimeSpan.FromSeconds(Math.Pow(2, retryAttempt)))
	.ExecuteAsync(
		async () =>
		{
			await eventHub.RefreshAsync();
			var result = await eventHub.ListAuthorizationRulesAsync();
			
			if (result.Count() < 2) // Count should be 2, because WithNewSendRule & WithNewListenRule is set
			{
				throw new InvalidOperationException("Not all AuthorizationRules where created!");
			}

			return result;
		});
```

**Expected behavior**
SendRule and ListenRule should be created and can be Listed correctly.

**Screenshots**
-

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : Rider, VS, Azure DevOps Hosted Build Agent, .NET Core 2.2
 - Version of the Library used:
 
    - Microsoft.Azure.Management.Fluent Version="1.27.2
    - Microsoft.Azure.Management.ResourceManager.Fluent Version="1.27.2"

**Additional context**
The problem starts on Monday (2019.11.14) and was detected by our system tests, which runs on an Azure DevOps HostedAgent (Image: windows-2019). Before Monday everything was fine.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by yaohaizh** [comment] 2019-11-18 03:19
@weidongxu-microsoft could you help take a look at this one? Thanks.

**Comment by weidongxu-microsoft** [comment] 2019-11-18 04:50
@MariuszKogut It appears to be intermittent. A possible cause under investigation is concurrent call to create SendRule and ListenRule in parellel. Service might not like this.

Before this issue got triaged and fixed, separate SendRule and ListenRule should help:
```
var eventHub = await azure.EventHubs.Define(eventHubName)
	.WithExistingNamespace(eventHubNamespace)
	.WithPartitionCount(1) // Use only 1 partition, to avoid that event order is destroyed. 
	.WithNewSendRule(Names.EventHubNamespace.SendRule)
	.CreateAsync();

await eventHub.Update()
	.WithNewListenRule(Names.EventHubNamespace.ListenRule)
	.ApplyAsync();
```

**Comment by weidongxu-microsoft** [comment] 2019-11-18 05:24
@jfggdl
Hello Javier. Could you help confirm whether event hub support concurrency on these REST API calls?
```
PUT /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.EventHub/namespaces/{namespaceName}/AuthorizationRules/{authorizationRuleName}
```
It is called with same {resourceGroupName}, same {namespaceName}, and same {authorizationRuleName} (basically a same event hub), with different payload (e.g. "rights":"Listen", and "rights":"Send").

Related [spec](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/eventhub/resource-manager/Microsoft.EventHub/stable/2017-04-01/EventHub.json#L498)

**Comment by MariuszKogut** [comment] 2019-11-18 06:28
@weidongxu-microsoft 
> Before this issue got triaged and fixed, separate SendRule and ListenRule should help:

I can confirm that this fixes my problem at the moment.  Thank you very much for your support.

**Comment by nickzhums** [comment] 2020-01-15 07:39
@MariuszKogut Closing this issue as it is resolved

**Closed by nickzhums** 2020-01-15 07:39 UTC
Labels: Bug, Event Hubs, Mgmt, Service Attention

**Comment by weidongxu-microsoft** [comment] 2020-01-20 07:54
@nickzhums 

Workaround is provided, but root cause is still waiting for service confirmation.

**Comment by QingpingMeng** [comment] 2020-05-01 06:08
Samething happens when adding two rules to ServiceBus queue.
```
serviceBusNamespace.Queues.Define(requestQueueName)
                .WithExpressMessage()
                .WithNewListenRule(listenKeyRuleName)
                .WithNewSendRule(sendKeyRuleName)
                .CreateAsync(cancellationToken).ConfigureAwait(false);
```

Above code only adds the Send Rule. With the workaround it fixes the issue but I don't think this should be closed as the library is not working as expected.

**Comment by MariuszKogut** [comment] 2020-05-01 07:45
Yeah. It's a very common usecase to add both rules in one service call. I was searching for hours, what is going on here...
