### ISSUE TITLE
[BUG] Cannot bind custom domain

### ISSUE THREAD

**Issue by rybkov** [Azure/azure-libraries-for-net#646] opened 2019-04-20 18:11 UTC
**Describe the bug**
Cannot bind custom domain to AppService

***Exception or Stack Trace***
Using from Azure Function on Local Machine, call just stuck and does not return with any errors

**To Reproduce**
Get AppService (in my case using GetByIdAsync)
Call host name binding

***Code Snippet***
`App?.Update( ).DefineHostnameBinding( ).WithThirdPartyDomain( HostName ).WithSubDomain( SubDomainName ?? "" ).WithDnsRecordType( String.IsNullOrEmpty( SubDomainName ) ? CustomHostNameDnsRecordType.A : CustomHostNameDnsRecordType.CName ).Attach( ).Apply( );`

**Expected behavior**
Code worked couple months ago, and since that time stopped

**Setup:**
 - OS: Winsows 10
 - IDE : Visual Studio 2019
 - 1.21.0

**Comment by kurtzeborn** [comment] 2019-04-22 18:20
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by rybkov** [comment] 2019-09-13 19:01
Related issue, if domain is not setup in DNS, same hanging experience. 

Errors in the Output while Debugging

`Exception thrown: 'Microsoft.Rest.TransientFaultHandling.HttpRequestWithStatusException' in Microsoft.Rest.ClientRuntime.dll
Exception thrown: 'Microsoft.Rest.TransientFaultHandling.HttpRequestWithStatusException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Azure.Management.AppService.Fluent.Models.DefaultErrorResponseException' in Microsoft.Azure.Management.AppService.Fluent.dll
Exception thrown: 'Microsoft.Azure.Management.AppService.Fluent.Models.DefaultErrorResponseException' in System.Private.CoreLib.dll`

**Comment by weidongxu-microsoft** [comment] 2019-09-17 04:00
@rybkov
Yes, it is not apparent, but please use "@" for now.

The hanging is caused by error handling logic and retry logic (service reply 400 and client retry on it). It could take some time to solve (since the retry is generic logic and we need to be careful).

**Comment by weidongxu-microsoft** [comment] 2019-09-17 04:32
https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/AppService/WebAppBaseImpl.cs#L678

**Comment by rybkov** [comment] 2019-09-18 01:53
> @rybkov
> Yes, it is not apparent, but please use "@" for now.
> 
> The hanging is caused by error handling logic and retry logic (service reply 400 and client retry on it). It could take some time to solve (since the retry is generic logic and we need to be careful).

The bigger issue is that any error causing hanging with no way to stop it. The only workaround is to create task and the force it to stop, which is not elegant.

**Comment by weidongxu-microsoft** [comment] 2019-09-18 02:29
> > @rybkov
> > Yes, it is not apparent, but please use "@" for now.
> > The hanging is caused by error handling logic and retry logic (service reply 400 and client retry on it). It could take some time to solve (since the retry is generic logic and we need to be careful).
> 
> The bigger issue is that any error causing hanging with no way to stop it. The only workaround is to create task and the force it to stop, which is not elegant.

Yes, agree. Trying to internally figure out whether that is done with intention to circurmvent other issue unknown to me, or just stupid code bug.

**Comment by weidongxu-microsoft** [comment] 2019-10-18 04:40
Fixed in 1.27.1, to be released on Oct. 25th.

**Closed by weidongxu-microsoft** 2019-10-18 04:40 UTC
Labels: App Services, Mgmt
