### ISSUE TITLE
ExportTo  sqldb as bacpac to Storage stuck for longtime

### ISSUE THREAD

**Issue by vinothrao** [Azure/azure-libraries-for-net#835] opened 2019-10-14 10:25 UTC
**Describe the bug**
 I tried to use the ExportTo functionality to export the database as bacpac file to azure storage in Azure functions. But the function is stuck and after some time  resulted in an exception Microsoft.Rest.Azure.CloudException: 'Long running operation failed with status 'BadRequest'.'

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
   var creds = new AzureCredentialsFactory().FromServicePrincipal("", "", "", AzureEnvironment.AzureGlobalCloud);
            var azure = Azure.Authenticate(creds).WithSubscription("9");

            var sqldb = azure.SqlServers.Databases.ListBySqlServer("", "");
            var customerDb = sqldb.Single(x => x.Name == customerDetails.CustomerName);

            var storageAccount = azure.StorageAccounts.GetByResourceGroup("bacpactest", "bacpactest1");

             customerDb.ExportTo(storageAccount, "", "dbfromsample.bacpac").
                WithSqlAdministratorLoginAndPassword("", "").Execute();

**Expected behavior**
The bacpac should be uploaded to azure storage

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by vinothrao** [comment] 2019-10-20 06:54
Export as bacpac is taking long time through rest api it seems. The operation is stuck at this point  async Task<AzureOperationResponse<TBody, THeader>> GetPostOrDeleteOperationResultAsync<TBody, THeader>() . When i tried with bacpac dll it takes 10 min max for an empty db to export but with this Azure client it takes forever. 

We have a requirement to write an Azure function for this export.The problem is bacpac dll is not supporting .net core. So i am forced to write in .net framework which is Azure Function 1.0 runtime. I am thinking if i could figure this out then i can use .net core and Azure functions 2.0 runtime. Any help would be appreciated.

**Comment by yaohaizh** [comment] 2019-10-21 01:40
@ChenTanyi could you help follow with this case? Thanks.

**Comment by ChenTanyi** [comment] 2019-10-23 06:10
@vinothrao I cannot reproduce your problem. Does you run with any additional condition? What is your SDK version? Is your DB too large to export?

Here is my successful code: (the comment line is used for creation at first time to run)
```csharp
            if (isCreate)
            {
                try
                {
                    azure.ResourceGroups.DeleteByName(rgName);
                }
                catch { }
                azure.ResourceGroups.Define(rgName).WithRegion(region).Create();
            }

            //var sql = azure.SqlServers.Define("mysqlsersetsdgv")
            //    .WithRegion(region)
            //    .WithExistingResourceGroup(rgName)
            //    .WithAdministratorLogin(username)
            //    .WithAdministratorPassword(password)
            //    .DefineFirewallRule("test")
            //    .WithIPAddressRange("0.0.0.0", "255.255.255.255")
            //    .Attach()
            //    .Create();

            //var db = azure.SqlServers.Databases.Define("sqldblskdjfl")
            //    .WithExistingSqlServer(sql)
            //    .FromSample(SampleName.AdventureWorksLT)
            //    .Create();

            var sqldb = azure.SqlServers.Databases.ListBySqlServer(rgName, "mysqlsersetsdgv");
            var customerDb = sqldb.Single(x => x.Name == "sqldblskdjfl");

            var storageAccount = azure.StorageAccounts
                .Define("stlskjdl")
                .WithRegion(region)
                .WithExistingResourceGroup(rgName)
                .Create();

            customerDb.ExportTo(storageAccount, "from-sample", "dbfromsample.bacpac")
                .WithSqlAdministratorLoginAndPassword(username, password).Execute();
```
Also, it could be combined into the following code
```csharp
            azure.ResourceGroups.Define(rgName).WithRegion(region).Create();
            var sql = azure.SqlServers.Define("mysqlsersetsdgv")
                .WithRegion(region)
                .WithExistingResourceGroup(rgName)
                .WithAdministratorLogin(username)
                .WithAdministratorPassword(password)
                .DefineFirewallRule("test")
                .WithIPAddressRange("0.0.0.0", "255.255.255.255")
                .Attach()
                .DefineDatabase("sqldblskdjfl")
                .FromSample(SampleName.AdventureWorksLT)
                .Attach()
                .Create();

            var storageAccount = azure.StorageAccounts
                .Define("stlskjdl")
                .WithRegion(region)
                .WithExistingResourceGroup(rgName)
                .Create();

            sql.Databases.Get("sqldblskdjfl").ExportTo(storageAccount, "from-sample", "dbfromsample.bacpac")
                .WithSqlAdministratorLoginAndPassword(username, password).Execute();
```

**Comment by vinothrao** [comment] 2019-10-24 08:05
I created an empty DB from the Azure portal and tried to export. It took some 20 min to finish. I think that is the default behavior of export through REST as per this documentation : https://docs.microsoft.com/en-us/azure/sql-database/azure-sql-database-hangs-importing-exporting.

Any way we can finish the running once the request is accepted rather waiting for it to finish.

**Comment by ChenTanyi** [comment] 2019-10-25 02:05
@vinothrao the time I export the sql created above is just 39s. Maybe it depends on the service's behavior.

Thanks for your link, and thanks for your issue. I'll close it since it may be same behavior on each platform.

**Closed by ChenTanyi** 2019-10-25 02:05 UTC
Labels: Mgmt, SQL, customer-reported, needs-more-info

**Comment by vinothrao** [comment] 2020-01-08 09:39
@ChenTanyi  I need a help on this. As I said i require a synchronous version where i need  abort the operation once the export request is accepted instead waiting till it completes. I made the code changes for this one. Is it ok if i create a pull request for this?

**Comment by ChenTanyi** [comment] 2020-01-08 09:57
@vinothrao Yeah, every PR is welcome!

**Comment by vinothrao** [comment] 2020-01-23 07:21
I need a help here. I have put Rest request for export of an SQL DB. I got a firewall error like this IP does not have permission to access the DB. So i added that IP to firewall rule of the server. But my question is will this ip be same for every request? is there anywhere we have this ip list so that i can add these to firewall rules.

**Comment by ChenTanyi** [comment] 2020-01-23 09:36
@vinothrao It seems you want to add you public IP to SQL DB's white list. You can search the public IP for more information. Whether your public IP will be changed is based on you ISP. If you use a public IP got from ISP, it will not change. If you work behind a private network, you can ask the network administrators about the public IP list.

**Comment by vinothrao** [comment] 2020-01-23 12:16
As per my understanding this should not be my IP rather the cloud VM which is trying to access the SQL for exporting bacpac.

**Comment by ChenTanyi** [comment] 2020-01-25 05:08
@vinothrao If you are talking about the Azure VM IP, there is a resource with type "Public IP address", you can keep it running or use a static IP in order to make the public IP not changed. Otherwise, the IP will be changed when you deallocate the VM. (You can see an option in portal to keep the IP address when you stop the VM.)
