### ISSUE TITLE
[BUG] If you have a UserManagedIdentity that is null, you cannot bind SSL certificates, nor can you remove the UserManagedIdentity

### ISSUE THREAD

**Issue by carsontwilson** [Azure/azure-libraries-for-net#839] opened 2019-10-16 00:03 UTC
This took a few hours to figure out, so I'm hoping this can be addressed so as to save others time and suffering.

If you have a UserManagedIdentity assigned, and that UserManagedIdentity no longer exists in the Azure AD you will run into the following two problems:

**Problem One:**
When trying to execute the following code:
`
WebAppRm.Update()
                .DefineSslBinding()
                    .ForHostname(customHostName)
                    .WithExistingCertificate(CertificateThumbprint)
                    .WithSniBasedSsl()
                    .Attach()
                .Apply();
`

The system will just sit there forever (well, I gave up after a minute or two), with no response or errors. However, if you look at the Activity Log in the Azure Portal you'll see the following error:

`
Identity operation for resource '/subscriptions/xxxxx/resourceGroups/xxx/providers/Microsoft.Web/sites/xxxxx' failed with error 'Failed to perform resource identity operation. Status: 'BadRequest'. Response: '{"error":{"code":"BadRequest","message":"Resource '/subscriptions/xxxxx/resourcegroups/xxx/providers/Microsoft.ManagedIdentity/userAssignedIdentities/xxxx' was not found."}}'.'.
`

As well as:

`
There was a problem communicating with the identity service. Diagnostic information: timestamp '20191015T224818Z', subscription id xxxxx', tracking id 'xxxxx', request correlation id 'xxxxx'.
`

If you remove the UserManagedIdentity through the portal (more on that below), everything will work correctly.

**What should happen is...** it should just work. I'm not sure why an invalid UserManagedIdentity would prevent you from adding a SSL binding. It did not prevent me from doing other things, like adding a custom hostname for example. If that's not possible for some reason, at least return a meaningful error to the calling method, rather than just sitting there.

This leads to...

**Problem Two:**
If you try to remove a UserManagedIdentity through the Azure SDK, and that Identity does not exist, you get a null reference exception. It _seems_ like it wants to get the identity before it removes it (if I click on it in the portal it says resource not found).

Here's the little blob of code:

`
var identities = WebAppRm.UserAssignedManagedServiceIdentityIds;
            foreach (var identity in identities)
            {
                Console.WriteLine($"Removing identity id: {identity} from: {WebAppRm.Name}");
                WebAppRm.Update()
                    .WithoutUserAssignedManagedServiceIdentity(identity)
                    .Apply();
            }
`

Note that identities is populated with identities, so it can see them and knows they are there (in other words, it's not null).

**What should happen is...** it should just remove the Identity whether or not the identity itself is valid. If you remove it in the Portal it's fine. It should not matter whether it's valid or it exists, the important thing is you want the reference gone.

**Comment by yaohaizh** [comment] 2019-10-16 03:59
Please follow this issue of managed identity.

**Comment by ChenTanyi** [comment] 2019-10-22 10:09
@carsontwilson I can reproduce your problem one, but cannot reproduce your problem two.

We will discuss about fixing problem one.

If you still have problem about problem two, could you give more specific operation about it? Such as the whole code with SDK version, a gif or so on.
Thanks.

Here is my code for problem two, which work fine in latest SDK(1.27.0)
```csharp
            azure.ResourceGroups.Define(rgName).WithRegion(region).Create();

            var func = azure.AppServices.FunctionApps
                .Define("wkerkjhskdf")
                .WithRegion(region)
                .WithExistingResourceGroup(rgName)
                .Create();

            var identity = azure.Identities
                .Define("idksldfn")
                .WithRegion(region)
                .WithExistingResourceGroup(rgName)
                .Create();

            var id2 = azure.Identities
                .Define("klsjer")
                .WithRegion(region)
                .WithExistingResourceGroup(rgName)
                .Create();

            func.Update()
                .WithExistingUserAssignedManagedServiceIdentity(identity)
                .WithExistingUserAssignedManagedServiceIdentity(id2)
                .Apply();

            azure.Identities.DeleteByResourceGroup(rgName, "idksldfn");

            foreach (var id in func.UserAssignedManagedServiceIdentityIds)
            {
                Console.WriteLine($"Remove id: {id}");
                func.Update()
                    .WithoutUserAssignedManagedServiceIdentity(id)
                    .Apply();
            }
```

**Comment by carsontwilson** [comment] 2019-10-22 18:24
It will take me a little bit to get back to you this, but my SDK is one minor version behind (I'm on 1.26). I'll update to 1.27 and try from there

**Comment by ChenTanyi** [comment] 2019-11-19 01:37
@carsontwilson it seems you don't meet the bugs again? I'll close the issue, feel free to reopen it if you still meet it.

**Closed by ChenTanyi** 2019-11-19 01:37 UTC
Labels: Managed Identity, Mgmt
