### ISSUE TITLE
[FEATURE REQ] Allow setting custom health probe headers on traffic manager profile

### ISSUE THREAD

**Issue by AlexEyler** [Azure/azure-libraries-for-net#705] opened 2019-06-17 20:45 UTC
**Is your feature request related to a problem? Please describe.**
Right now, it's only possible to update each traffic manager *endpoint* with custom headers. Traffic Manager Profiles support setting a default collection of custom headers, but it's just not possible in Fluent yet.

**Describe the solution you'd like**
Update `IWithCreate` and `IUpdate` for traffic manager to allow setting the custom health probe headers.

Alternatively, add an overload to WithHttpsMonitoring and WithHttpMonitoring that allows passing in custom health probe headers.

**Describe alternatives you've considered**
The alternative is to update each endpoint, but I'd prefer to be able to update the defaults in the traffic manager profile

**Comment by praries880** [comment] 2019-06-17 22:40
Thank you for opening this issue! We are routing it to the appropriate team for follow up.


@yaohaizh  Can you kindly take a look at this?

**Comment by rohinkoul** [comment] 2019-11-26 22:12
Since this is a product feature request. Please create an item on user voice https://feedback.azure.com/forums/217313-networking?category_id=367312

@praries880 please close this issue here.

**Comment by yaohaizh** [comment] 2019-11-27 01:26
@rohinkoul, we need keep the issue open to track the status. Please let us know when you have the API(swagger spec) ready for us support this feature.

**Comment by rohinkoul** [comment] 2019-11-27 22:14
@yaohaizh this is not a bug in the service or API interface. This is a new feature request. This may or may not make it to the product based on votes it receives on the UserVoice. I don't see the point of keeping the issue open here. At this point, we can't commit to supporting this feature.

**Comment by yunbas** [comment] 2020-02-24 10:10
@AlexEyler this seems to be doable with current TrafficManager Fluent libraries. For your reference, this is what I did:

            IAzure azure = Azure.Authenticate(credentials).WithDefaultSubscription();
            string rgName = "profile-test";
            string profileName = SdkContext.RandomResourceName("profile-test-", 20);
            IWithEndpoint tmDefinition = azure.TrafficManagerProfiles
                    .Define(profileName)
                    .WithExistingResourceGroup(rgName)
                    .WithLeafDomainLabel(profileName)
                    .WithPriorityBasedRouting();

            var tmCreatable = tmDefinition.DefineExternalTargetEndpoint("example")
                .ToFqdn("www.example.com")
                .FromRegion(Region.USEast2)
                .WithRoutingPriority(1)
                .Attach();
            var trafficManagerProfile = tmCreatable.Create();
            trafficManagerProfile.Inner.MonitorConfig.CustomHeaders = new List<MonitorConfigCustomHeadersItem>();
            trafficManagerProfile.Inner.MonitorConfig.CustomHeaders.Add(new MonitorConfigCustomHeadersItem("newheader", "newvalue"));
            trafficManagerProfile.Update().Apply();

**Comment by KarenHammons** [comment] 2020-02-24 22:04
@AlexEyler please let us know if there are still issues/questions.  The code sample above shows how to accomplish this already.  We'll close this issue.  Thank you.

**Closed by KarenHammons** 2020-02-24 22:04 UTC
Labels: Feature Request, Mgmt, Network - Traffic Manager, Service Attention, customer-reported
