### ISSUE TITLE
[BUG] Receiving System.MissingMethodException: Method not found: 'Void Microsoft.Rest.TokenCredentials..ctor(Microsoft.Rest.ITokenProvider, System.String, System.String)'.

### ISSUE THREAD

**Issue by sierks** [Azure/azure-libraries-for-net#1102] opened 2020-07-10 16:10 UTC
**Describe the bug**
Getting an exception when I try any commands from the "azure" object.

***Exception or Stack Trace***
System.MissingMethodException: Method not found: 'Void Microsoft.Rest.TokenCredentials..ctor(Microsoft.Rest.ITokenProvider, System.String, System.String)'.

***Code Snippet***
```
var azure = Microsoft.Azure.Management.Fluent.Azure
    .Authenticate(credentials)
    .WithDefaultSubscription()
    ;

//both of these lines throw the exception
var l = await azure.VirtualMachines.ListAsync();
var webapp = azure.WebApps.GetByResourceGroup(resourceGroup, name);
```

**Setup (please complete the following information):**
 - IDE : VS 2019
 - Version of the Library used:  
1.34.0 for Microsoft.Azure.Management.Fluent
2.3.20 for Microsoft.Rest.ClientRuntime
3.3.19 for Microsoft.Rest.ClientRuntime.Azure
2.4.0 for Microsoft.Rest.ClientRuntime.Azure.Authentication

**Additional context**
.NET 4.7.2

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X (Code Snippet)] Repro Steps Added
- [X] Setup information Added

**Comment by sierks** [comment] 2020-07-10 16:15
Upgrading Microsoft.Rest.ClientRuntime to 2.3.21 and Microsoft.Rest.ClientRuntime.Azure.Authentication to 2.4.1 seems to have resolved the issue...

**Comment by ChenTanyi** [comment] 2020-07-13 02:38
@sierks thanks for reporting that.

**Comment by ChenTanyi** [comment] 2020-07-13 09:20
@sierks I cannot reproduce you problem in your target version:
![image](https://user-images.githubusercontent.com/15213781/87287718-05385700-c52d-11ea-937f-e2124c912d74.png)
![image](https://user-images.githubusercontent.com/15213781/87287768-14b7a000-c52d-11ea-9e6a-3220d4c8717d.png)

**Comment by ChenTanyi** [comment] 2020-07-13 09:22
@sierks Since you have solved your problem by updating version. If you won't test with the previous version, I will close it. Otherwise, could you please give more information about how to reproduce it?

**Comment by sierks** [comment] 2020-07-13 19:20
I am creating my credentials differently than you are. But otherwise yes, it is working for me on the newer packages, so you can close it.

```
            var credentials = SdkContext.AzureCredentialsFactory
                .FromServicePrincipal(clientId,
                    clientSecret,
                    tenantId,
                    AzureEnvironment.AzureGlobalCloud);

```

**Comment by ChenTanyi** [comment] 2020-07-14 02:29
@sierks Thanks. 

We have met one MissingMethodException during upgrading, maybe it is due to the upgrading. The exception doesn't show anytime later it.
If you meet it again, welcome to report it here.

**Closed by ChenTanyi** 2020-07-14 02:29 UTC
Labels: Authentication
