### ISSUE TITLE
[BUG] Upload certificate throws exception Operation returned an invalid status code 'Conflict'

### ISSUE THREAD

**Issue by rybkov** [Azure/azure-libraries-for-net#724] opened 2019-07-04 15:06 UTC
**Describe the bug**
When you call binding certificate to a host name it gives an exception 
`App.Update( ).DefineSslBinding( ).ForHostname( DomainName ).WithPfxCertificateToUpload( CertificatePath, CertificatePassword ).WithSniBasedSsl( ).Attach( ).Apply( );`

If upload certificate via Azure Portal - it works

Issue is that request is wrong as it gets Thumbprint from another certificate somehow (even from antoher app service)

***Request***
{
	"properties": {
		"enabled": true,
		"hostNameSslStates": [{
				"name": "hostname",
				"sslState": "SniEnabled",
				"thumbprint": "2202DEAC88404530105D6AB9BC8BFEC8747096B2",
				"toUpdate": true
			}			
		],
		"serverFarmId": "/subscriptions/xxxxxxxxxx/resourceGroups/appservices/providers/Microsoft.Web/serverfarms/yyyyyyyy",
		"reserved": false,
		"isXenon": false,
		"hyperV": false,
		"scmSiteAlsoStopped": false,
		"clientAffinityEnabled": false,
		"clientCertEnabled": false,
		"hostNamesDisabled": false,
		"containerSize": 0,
		"dailyMemoryTimeQuota": 0,
		"httpsOnly": false,
		"redundancyMode": "None"
	},
	"identity": {
		"type": "SystemAssigned"
	},
	"kind": "app",
	"location": "North Central US",
	"tags": {
		"hidden-related:/subscriptions/xxxxxxxx/resourceGroups/appservices/providers/Microsoft.Web/serverfarms/yyyyyyy": "empty"
	}
}

***Response***
{
	"Code": "Conflict",
	"Message": "The certificate with thumbprint '2202DEAC88404530105D6AB9BC8BFEC8747096B2' does not match the hostname 'xxxxxxxxx'.",
	"Target": null,
	"Details": [{
				"Message": "The certificate with thumbprint '2202DEAC88404530105D6AB9BC8BFEC8747096B2'
				does not match the hostname 'xxxxxxxxx'.
				"},{"
				Code ":"
				Conflict "},{"
				ErrorEntity ":{"
				ExtendedCode ":"
				04030 ","
				MessageTemplate ":"
				The certificate with thumbprint '{0}'
				does not match the hostname '{1}'.
				","
				Parameters ":["
				2202 DEAC88404530105D6AB9BC8BFEC8747096B2 ","
				xxxxxxxxxx "],"
				Code ":"
				Conflict ","
				Message ":"
				The
				certificate with thumbprint '2202DEAC88404530105D6AB9BC8BFEC8747096B2'
				does not match the hostname 'xxxxxxxx'.
				"}}],"
				Innererror ":null
}

***Exception or Stack Trace***
Operation returned an invalid status code 'Conflict'

>  at Microsoft.Azure.Management.AppService.Fluent.WebAppsOperations.BeginCreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String name, SiteInner siteEnvelope, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.AppService.Fluent.WebAppsOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String name, SiteInner siteEnvelope, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.AppService.Fluent.WebAppsOperationsExtensions.CreateOrUpdateAsync(IWebAppsOperations operations, String resourceGroupName, String name, SiteInner siteEnvelope, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.AppService.Fluent.AppServiceBaseImpl`6.CreateOrUpdateInnerAsync(SiteInner site, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.AppService.Fluent.WebAppBaseImpl`5.CreateResourceInternalAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Management.AppService.Fluent.WebAppBaseImpl`5.CreateResourceAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.IResourceCreator<IResourceT>.CreateResourceAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.CreatorTaskItem`1.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.TaskGroupBase`1.ExecuteNodeTaskAsync(DAGNode`1 node, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.CreatableUpdatable`5.ApplyAsync(CancellationToken cancellationToken, Boolean multiThreaded)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.Extensions.Synchronize[TResult](Func`1 function)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.CreatableUpdatable`5.Apply()

**Setup:**
 - OS: Windows
 - Environment: Local and Azure Functions (both affected)
 - Microsoft.Azure.Management.Fluent 1.23.0

**Comment by rybkov** [comment] 2019-07-04 15:56
***Temporary Solution***
`var certs = AzureManager.Connector.AppServices.AppServiceCertificates;
            var certificate = await certs.Define( $"{Thumbprint}##{region}#" ).WithRegion( region ).WithExistingResourceGroup( RESOURCE_GROUP ).WithPfxFile( CertificatePath ).WithPfxPassword( CertificatePassword ).CreateAsync(  );

            var updateApp = await App.Update( ).DefineSslBinding( ).ForHostname( DomainName ).WithExistingCertificate( certificate.Thumbprint ).WithSniBasedSsl( ).Attach( ).ApplyAsync( );`

**Comment by maggiepint** [comment] 2019-07-08 23:27
Thanks for this feedback. I have routed to the appropriate team for follow up.

**Comment by ChenTanyi** [comment] 2020-01-13 07:33
@rybkov I cannot reproduce you problem. Does your certificate match the domain?
I can only reproduce it when I use a wrong domain.

Version: Fluent 1.29.0 in Windows 10

**Comment by rybkov** [comment] 2020-01-14 02:39
@ChenTanyi it did match

**Comment by ChenTanyi** [comment] 2020-01-14 04:03
@rybkov Can you give me an example crt and key (could be just self-signed) and the domain which can reproduce this issue?

**Comment by ChenTanyi** [comment] 2020-01-14 04:10
By the way, could you CNAME the domain to "lskjdf.azurewebsites.net"? Then I could test it.

**Comment by ChenTanyi** [comment] 2020-01-19 07:59
@rybkov Since the implementation of the `WithPfxCertificateToUpload` is **actually the same as** your ***Temporary Solution***, if you cannot provide any certificate to reproduce this problem, I cannot test to find where the problem is.

Btw, if the only reproducible certificate is very import (That it cannot be reproduced by other certificate is really a corner case), you could add the response of `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/certificates/{name}` here during the request. I think it may help a little.

**Comment by yaohaizh** [comment] 2020-01-23 01:50
@rybkov, given this, we are closing this issue now. Please feel free to open/re-open issues if you have more issues. Thanks!

**Closed by yaohaizh** 2020-01-23 01:50 UTC
Labels: App Services, Mgmt, customer-reported, customer-response-expected
