### ISSUE TITLE
System.Reflection.AmbiguousMatchException

### ISSUE THREAD

**Issue by KoditkarVedant** [Azure/azure-libraries-for-net#24] opened 2017-09-28 05:56 UTC
```
System.Reflection.AmbiguousMatchException
Multiple custom attributes of the same type found.
```

**StackTrace**:
```

System.Attribute.GetCustomAttribute
Microsoft.Rest.ServiceClient`1.get_FrameworkVersion
Microsoft.Rest.ServiceClient`1.get_DefaultUserAgentInfoList
Microsoft.Rest.ServiceClient`1.SetUserAgent
Microsoft.Rest.ServiceClient`1.InitializeHttpClient
Microsoft.Azure.Management.Sql.Fluent.SqlManagementClient..ctor

```

I'm using Microsoft.Azure.Management.Sql.Fluent for do some operations on the database. My Code works just fine on my local environment but when I deploy it on Azure(Web app) and try to do the same operation it throws this exception.

Sample Code: (I can not share the actual code but this is all I can do)

```
var authContext = getAuthenticationContext(getAutority());
var clientCredential = getClientCredential(clientId, appKey);
var token = authContext.AcquireTokenAsync(resource, clientCredential).Result;            
   
var tokenCredentials = new TokenCredentials(token.AccessToken);         
// on this line it is throwing the error
var resourceClient = new ResourceManagementClient(tokenCredentials) { SubscriptionId = subscriptionId };
```

**Comment by milismsft** [comment] 2017-09-28 18:11
In the code sample you shared I don't see anything that can trace the exception back to SqlManagementClient; the call to ResourceManagementClient() will most certainly not going to call it.

To get a stack trace like the one you shared I would expect in your code to execute something similar to:

var resourceClient = SqlManager.Configure().Authenticate(new AzureCredentials(new ServicePrincipalLoginInformation { ClientId = clientId, ClientSecret = appKey }, tenantId, AzureEnvironment.AzureGlobalCloud), subscriptionId);

**Comment by milismsft** [comment] 2017-09-28 18:27
btw this might be related to https://github.com/Azure/autorest/issues/1542

**Comment by KoditkarVedant** [comment] 2017-09-29 04:08
@milismsft I'm sorry to put sample code which make use ResourceManagerClient instead of SqlManagementCient as my stack trace is for SqlManagementClient but the main thing is this same exception is also thrown when we use ResourceManagerClient on Azure.

**Comment by KoditkarVedant** [comment] 2017-10-07 06:23
@hovsepm It seems like your pull request is not passed all the checks can you please look into that. It's bee n a week that pull request still not merged yet. Can I fix these and create a new pull request for this issue?

**Comment by hovsepm** [comment] 2017-11-08 21:46
@KoditkarVedant the issue is not in the code but in the build process. Weren't you able to work it around with the suggestions from AutoRest issue suggested by @milismsft ? You should be able to run the code after updating AppInsights dependencies on your environment.

**Comment by hovsepm** [comment] 2018-10-18 23:02
Closing as by design.

**Closed by hovsepm** 2018-10-18 23:02 UTC
