### ISSUE TITLE
not able to create premium osdisk with vm 

### ISSUE THREAD

**Issue by bankzitter01** [Azure/azure-libraries-for-net#193] opened 2018-03-02 15:25 UTC
I am using the following code to create a vm:
```
var linuxVM = azure.VirtualMachines.Define(vmName)
                        .WithRegion(location)
                        .WithExistingResourceGroup(resourceGroup.Name)
                        .WithNewPrimaryNetworkInterface(networkInterface)
                        .WithPopularLinuxImage(image)
                        .WithRootUsername(adminUser)
                        .WithRootPassword(adminPwd)
                        .WithSize(virtualMachineSizeTypes)
                        .WithOSDiskName(vmSetting.OsDisk.Name)
                        .WithOSDiskCaching(vmSetting.OsDisk.CachingType)
                        .WithExistingAvailabilitySet(availabilitySet)
                        .WithNewStorageAccount(storageAccount)
                        .Create();
```
I am missing a WithStorageAccountType to generate a vm with a premium os disk.

**Comment by bankzitter01** [comment] 2018-03-08 10:43
I have found a work a round. After adding the data disks as included I need to stop the vm. Change the account type from standard to premium. It is a pity this cannot be done while creating. Or am I missing functionality?

**Comment by anuchandy** [comment] 2018-03-08 19:40
@bankzitter01 you could use following flow to specify the storage account type for OS Disk

```C#
                var vm = azure.VirtualMachines
                    .Define(vmName)
                    .WithRegion(location)
                    .WithNewResourceGroup(rgName)
                    .WithNewPrimaryNetwork("10.0.0.0/28")
                    .WithPrimaryPrivateIPAddressDynamic()
                    .WithoutPrimaryPublicIPAddress()
                    .WithPopularLinuxImage(KnownLinuxVirtualMachineImage.UbuntuServer14_04_Lts)
                    .WithRootUsername("Foo12")
                    .WithRootPassword("BaR@12abc!")
                    .WithOSDiskStorageAccountType(StorageAccountTypes.PremiumLRS)
                    .WithSize(VirtualMachineSizeTypes.StandardD3V2)
                    .Create();

```

**Comment by bankzitter01** [comment] 2018-03-16 12:38
Hey Anuchandy.

Thank you. I think you are right. I thought i have check everything. I should not have missed this. Sorry.

**Comment by hovsepm** [comment] 2018-10-18 23:00
Closed as by design.

**Closed by hovsepm** 2018-10-18 23:00 UTC
