### ISSUE TITLE
[BUG] Fluent.Core.Resource.Definition WithTag and WithTags does not work, no tags are added

### ISSUE THREAD

**Issue by AlexandruMaxim** [Azure/azure-libraries-for-net#755] opened 2019-07-30 15:42 UTC
**Describe the bug**
*WithTag* and *WithTags* from interface *IDefinitionWithTags<T>* does not work, no tags are added after CreateAsync() is done.

**To Reproduce**
1. define a new account
2. add tags using WithTag / WithTags.
3. check the body of the request, it does not contain any tag added in the step 2. The account is created but it does not contain any tag.

**Fluent Version**
1.23.0

***Code example***
```
account = StorageAccounts.Define(name)
                .WithRegion(region)
                .WithExistingResourceGroup(resourceGroupName);

account = account.WithSku(sku);
account = account.WithOnlyHttpsTraffic();
account = account.WithBlobStorageAccountKind();
account = account.WithTags(tags);

account.CreateAsync();
```
Also, when running with the debugger, the account object has the tags added, I think something is happenning when the request is created and send.

<img width="1278" alt="tagshiding" src="https://user-images.githubusercontent.com/52669535/62275343-69f8bf80-b44a-11e9-9484-53a46a03de84.png">

You are hiding the `Tags` variable with the `Tags` from `Inner` Interface which is 0.
ResourceManagement\Storage\StorageAccountImpl.cs:269

If you have any workaround, I would like to know.
Thanks!

**Comment by yaohaizh** [comment] 2019-07-30 15:46
@AlexandruMaxim Could you help provide some example code snippet for us to follow up more clearly? Thanks.

**Comment by yaohaizh** [comment] 2019-07-30 21:59
And what is your fluent version used?

**Comment by AlexandruMaxim** [comment] 2019-07-31 07:47
@yaohaizh I've added the information in the issue report

**Comment by yaohaizh** [comment] 2019-07-31 07:51
The version you used are quite outdated, could you try the latest one (v1.24.0). Thanks.

**Comment by AlexandruMaxim** [comment] 2019-07-31 10:09
Hello, i use v1.23, it was a mismatch between the config and visual studio.

**Comment by AlexandruMaxim** [comment] 2019-08-01 07:50
I used the debugger, it seems you are hiding the variable Tags with the Tags from Inner interface. @yaohaizh I have attached a printscreen of the issue. ResourceManagement\Storage\StorageAccountImpl.cs:269

**Comment by yaohaizh** [comment] 2019-08-06 04:59
@AlexandruMaxim The issue is fixed on https://github.com/Azure/azure-libraries-for-net/commit/1c533240ded97dd184ccd8c6d7e896d179a8e03f. Please use the version of v1.24 and let me know the result. Thanks.

**Comment by AlexandruMaxim** [comment] 2019-08-08 12:34
Ok, thank you!

**Closed** 2019-08-08 13:52 UTC
Labels: Mgmt, customer-reported, needs-more-info
