### ISSUE TITLE
Question: Is SQL Fluent API Support Elastic Pool Pricing Tier Change 

### ISSUE THREAD

**Issue by ajaysingh77** [Azure/azure-libraries-for-net#330] opened 2018-05-17 17:05 UTC
Hi,

I want to change my elastic pool from standard to v-core based purchasing option and then downgrade back to standard. Is current implementation SQL fluent supports this. If not any reference to achieve this. 

Thanks,
Ajay Singh

**Comment by milismsft** [comment] 2018-05-17 18:35
@ajaysingh77 v-core based elastic pools are not currently supported in the Fluent SDK since these are a recent addition to SQL. You can try to convert an existing elastic pool to a v-core one via the Azure Portal or Azure CLI commands if that is something you can do.
Is this missing feature blocking you or it is more of an experimental try?

**Comment by ajaysingh77** [comment] 2018-05-18 05:42
I am using v-core for one my project. They are some scenario in which DTU based tier is not meeting my requirement in cost effective way compared to v-core. So to me it's a blocking. Apart from Azure Portal or Azure CLI, is rest api available to work with v-core? if yes I can write custom code to handle this.

**Comment by milismsft** [comment] 2018-05-20 09:19
@ajaysingh77 the REST API's are described in the Azure Autorest Swagger specs at https://github.com/Azure/azure-rest-api-specs/blob/master/specification/sql/resource-manager/Microsoft.Sql/preview/2017-10-01-preview/elasticPools.json

**Comment by ajaysingh77** [comment] 2018-05-20 19:04
I am using the following code to update the pool programatically
```
string _url = "https://management.azure.com/subscriptions/{0}/resourceGroups/{1}/providers/Microsoft.Sql/servers/{2}/elasticPools/{3}?api-version=2017-10-01-preview";

var url = string.Format(_url, _subcriptionId, _devResourceGroup, _sqlServerName, _elasticPoolName);
var request = new HttpRequestMessage(new HttpMethod("PATCH"), url);
request.Content = new StringContent(scaleDetails.ToString(), Encoding.UTF8, "application/json");//CONTENT-TYPE header

CancellationToken token = new CancellationToken();
wait _credentials.ProcessHttpRequestAsync(request, token);
where _credentials if of type AzureCredentials and 
scaleDetails is json object mentioned
{
  "sku": {
    "name": "GP_Gen4",
    "tier": "GeneralPurpose",
    "capacity": 4
  },
  "properties": {
  	"perDatabaseSettings": {
      "minCapacity": 0,
      "maxCapacity": 4
    },
    "maxSizeBytes": "494994980864",
    "zoneRedundant": false,
    "licenseType": "LicenseIncluded"
  }
}
```
but it's not doing anything. If I am testing the same code from postman things are working fine. Can you please let me know whether AzureCredentials.ProcessHttpRequestAsync is right approach for calling azure api? I am using this as it helps to reduce the code to get the access token, requires in Authorization header.

**Comment by milismsft** [comment] 2018-06-08 15:49
@ajaysingh77 I would recommend you use the non-Fluent .NET SDK instead (https://www.nuget.org/packages/Microsoft.Azure.Management.Sql/1.16.0-preview) which should have the features you are looking for.

**Comment by hovsepm** [comment] 2018-10-18 22:57
Closed as by design.

**Closed by hovsepm** 2018-10-18 22:57 UTC
