### ISSUE TITLE
Library generates Bad Request for networkInterfaces resource metrics

### ISSUE THREAD

**Issue by kierenj** [Azure/azure-libraries-for-net#181] opened 2018-02-25 12:14 UTC
I'm enumerating all resources, then all metrics, and requesting the last our of metrics on a minute granularity.

I get a Bad Request response, with no further info, only for a networkInterfaces resource, n BytesSentRate.  It's default agg is Total, which is what I request with.  Its the same error for any metrics on any networkInterfaces resource.

Where can I find out a way forward w/this?  In the portal, there are no metrics, in fact that resource doesn't appear at all.  Why then is it enumerable?  Should there be more error info?  Who else can I ask?

Thanks much.

**Comment by kierenj** [comment] 2018-02-26 10:56
Also getting bad requests for other resources types, which seems a different problem.  Where's the best place for me to seek support for this API?

**Comment by hovsepm** [comment] 2018-02-26 21:28
@kierenj I'll need to get more info to be able to route the issue correctly. Could you post here http traffic snapshots for the request and response? or alternatively could you post here a code snippet that fails?

**Comment by kierenj** [comment] 2018-02-27 08:12
As per https://social.msdn.microsoft.com/Forums/en-US/e3422837-b43a-4dba-8cb2-c8845f5f5207/using-monitormetrics-api-querying-any-networkinterfaces-resource-metrics-yields-bad-request?forum=WAVirtualMachinesVirtualNetwork -

Here's an anonymised request/response (zeroed-out GUIDs and anonymised resource refs/names):

`
GET https://management.azure.com//subscriptions/000aa2a6-000d-000e-000f-b41abd993000/resourceGroups/xx-xxxx-xxx000510259000/providers/Microsoft.Network/networkInterfaces/xx-xxxx/providers/microsoft.insights/metrics?timespan=2018-02-26T11%3A32%3A00.0000000Z%2F2018-02-26T13%3A32%3A00.0000000Z&interval=PT1M&metric=BytesSentRate&aggregation=Average%2CMinimum%2CMaximum%2CCount%2CTotal&resultType=Data&api-version=2017-05-01-preview HTTP/1.1
Connection: Keep-Alive
Accept-Language: en-US
Authorization: Bearer (REDACTED)
User-Agent: FxVersion/4.6.26020.03 Microsoft.Azure.Management.Monitor.Fluent.MonitorManagementClient/1.6.0.0 MacAddressHash/9b6b81e80ad4126a271306abaedd4660b1143f3edbd87790000510e08d6c079b
x-ms-client-request-id: 27fc0af0-a3d5-4bf4-b4d4-3bc5ce000000
Host: management.azure.com
`

And the response:

`
HTTP/1.1 400 Bad Request
Cache-Control: no-cache
__HandlingServerId__: shoeboxproxyeurope_shoeboxproxyeurope-red_MetricsMP_IN_5
Server: Microsoft-IIS/8.5
X-Powered-By: ASP.NET
x-ms-ratelimit-remaining-subscription-reads: 14944
x-ms-request-id: 4d93794a-a6f1-4ce4-b232-b23600000000
x-ms-correlation-request-id: 4d93794a-a6f1-4ce4-b232-b2364d6de123
x-ms-routing-request-id: UKWEST:20180226T123233Z:4d93794a-a6f1-4ce4-b232-b23600000000
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
Date: Mon, 26 Feb 2018 12:32:32 GMT
Content-Length: 0
`

**Comment by anirudhcavale** [comment] 2018-03-01 22:09
Hi @kierenj thanks for reporting these issues! So there are three distinct resources you seem to be having issues requesting for metrics; I'll answer them one by one:
1. NetworkInterfaces: We took a deeper look into this and realized the reason you're getting bad requests is because of a bug on our side. We are working on fixing this issue.
2. SQL: Some of the SQL metrics have a property (defined in their metric definitions) called "isDimensionRequired". For those metrics when querying for their values you must provide a filter for the dimension; if you do not do so the metric query will fail.
3. Redis: We followed up with the redis team on this, that particular metric was just recently added. It is still in the process of being rolled out; it may not have hit the region your redis resource is in just yet.

**Comment by kierenj** [comment] 2018-03-02 06:53
Ah that’s perfect, thank you. I tried to interpret the SQL error and understand what a dimension is but couldnt quite grasp it. If I have a metric, time range, granularity, what else is there? Different units? Could I be cheeky and ask for a quick example of how to filter for the dimension here?
All the other metrics across our tenants / subs query fine, so Im curious whats special about DTU stats for SQL:)
Bit of background, am building something to push all Azure stats to Elastic Cloud. Working great with these few exceptions :)

**Comment by anirudhcavale** [comment] 2018-03-02 18:24
@kierenj that's correct. The nature of the metric is that the it doesn't make sense to view these metrics at an aggregate level for the server; it makes most sense when analyzing a particular Database resoruce id or elastic pool resource id, so you must provide a filter for at least one of those dimensions.
Not cheeky to ask for an example; here's one:
In the example below I add a **filter** for the elastic pool resource id dimension (set it to *) so I get it back for all elastic pools resources on the server. 
ex. GET https://management.azure.com/subscriptions/<subid>/resourceGroups/<rg>/providers/Microsoft.SQL/servers/<serverName>/providers/microsoft.insights/metrics?timespan=2018-02-01T00:00:00Z/2018-02-01T01:00:00Z&interval=PT1M&metrics=storage_used& **$filter** =ElasticPoolResourceId eq '*'&aggregation=Average&resultType=Data&api-version=2017-05-01-preview

**Comment by kierenj** [comment] 2018-03-03 06:57
Ok I think I see that it’s like having sub-resource info, grouped at the resource level?  But pools and databases are all resources in their own right. Why not have the storage, dtu metrics on the pool and database resources themselves?

**Comment by anirudhcavale** [comment] 2018-03-06 22:16
@kierenj I'll follow up with SQL team on this duplication. Thanks for pointing it out. 
By the way, are we good to close this issue?

**Comment by kierenj** [comment] 2018-04-11 07:43
@anirudhcavale It would be great to know where/how I can ask further questions, or hear about the duplication issue mentioned above.?

I have a new issue around stats - CpuPercentage metric for App Service Plans is now doing something weird.

I'm trying to poll for new stats every minute, which in the vast majority of cases works fine.  It's tricky, because you can request stats for any time range (in the future even) and get results back, it's just that they are all 0 values.

I was using the fact that for each time bucket, the "count" value for items which haven't happened yet is 0.  So I work backwards in time - ignoring the 0-count buckets, then the final one left is the "current" stat, which I found is subject to change - so I ignore that one too, and take all the results prior to that.

HOWEVER, now, for CpuPercentage on App Service Plans, and I think on other resources too, the Count for future time buckets is coming back as "1".

The problems I have are:

0. (I don't know the most appropriate place to ask these questions ;))
1. Using the computer clock to know which stats are complete and good to log is bad, because I can't guarantee sync
2. Some stat values have a large latency (some minutes) it seems, so I can't just delay stats for 2 minutes or something (and don't want to!)
3. I can't just ignore "0" values (Average/Minimum/Maximum) fields, because that might be the real data values

This seems to have changed only recently.  What I really want is some direction please on how I can understand when new stats available, so that I can log them.

My actual use case is that I'm logging to JSON files, which are read by Filebeat and pushed to Elasticsearch to appear in Kibana.  It was working great for a while.. but I need to this to be solid!

Any help or pointers appreciated!

**Comment by yaohaizh** [comment] 2019-10-13 08:23
Could log issues for common Azure service issue here: https://github.com/Azure/azure-rest-api-specs

Close this as it not updated recent. @kierenj, feel free to open this issue if you think the issue is still relevant.

**Closed by yaohaizh** 2019-10-13 08:23 UTC
