### ISSUE TITLE
Fluent libraries are pinned to a single version of ADAL

### ISSUE THREAD

**Issue by stankovski** [Azure/azure-libraries-for-net#128] opened 2018-01-08 19:22 UTC
Fluent libraries are pinned to a single version of ADAL via Microsoft.Rest.ClientRuntime.Azure.Authentication making it impossible to use them with any other package that relies on ADAL

**Comment by hovsepm** [comment] 2018-01-11 23:58
Duplicate of https://github.com/Azure/azure-sdk-for-net/issues/3787

**Comment by hovsepm** [comment] 2018-02-01 19:04
fixed in Fluent SDK v1.6

**Closed by hovsepm** 2018-02-01 19:04 UTC
