### ISSUE TITLE
Could not load file or assembly, when using the Azure Fluent SDK and the Microsoft.Azure.Services.AppAuthentication (MSI) library

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-libraries-for-net#453] opened 2018-08-30 23:24 UTC
At the moment we are building an Azure Function within Visual Studio 2017 that retrieves information from a Azure Key Vault. 

The information retrieved from the key vault is used to authenticate the Fluent API. When we try this we get the below exception. it seems there is a hard dependency to this dll.

"Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Function1 ---> System.AggregateException : One or more errors occurred. ---> Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=2.28.3.860, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies."

We are using nuget packages:

- Microsoft.Azure.Management.Fluent 1.14.0
- Microsoft.Azure.Management.Graph.RBAC.Fluent 1.14.0
- Microsoft.Azure.Management.ResourceManager.Fluent 1.14.0
- Microsoft.Azure.Services.AppAuthentication 1.0.3
- Microsoft.NET.Sdk.Functions 1.0.14

**Comment by hovsepm** [comment] 2018-08-31 00:03
@maikvandergaag  @mopede80 please upgrade to Fluent SDK v.1.15.1 and let me know if you still have this issue.

**Comment by olandese** [comment] 2018-09-25 08:57
> I upgraded to Fluent SDK v.1.15.1 and I am still having this issue. I am getting the following error:
> 
> Microsoft.Rest.ClientRuntime.Azure.Authentication: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.14.0.8, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
> 
> We are using nuget packages:
> 
> Microsoft.Azure.Management.Graph.RBAC.Fluent 1.15.1
> Microsoft.Azure.Services.AppAuthentication 1.0.3
> Microsoft.NET.Sdk.Functions 1.0.22

Same problem

**Comment by hovsepm** [comment] 2018-09-27 22:48
if your target framework is 4.5.2 I think this is unfortunate but by design issue. Microsoft.Azure.Services.AppAuthentication v1.0.3 depends on Microsoft.IdentityModel.Clients.ActiveDirectory (>= 3.14.2) while Fluent SDK depends on Microsoft.Rest.ClientRuntime.Azure.Authentication 2.3.4 which in .Net 4.5.2 has hard dependency on Microsoft.IdentityModel.Clients.ActiveDirectory v2.28.3 due to backward compatibility issues. 

Could you migrate the project to .Net Core?

**Comment by hovsepm** [comment] 2018-09-27 22:48
@shahabhijeet could you take a look as well?

**Comment by hovsepm** [comment] 2018-10-18 22:46
Closing as by design. Please open a new issue if you hit this in v1.16.1 or higher in .Net Framework > 4.6.1 or .Net Core projects.

**Closed by hovsepm** 2018-10-18 22:46 UTC
