### ISSUE TITLE
Please update references to ADAL v4.4.0 which contains a lot of important fixes.

### ISSUE THREAD

**Issue by SIGAN** [Azure/azure-libraries-for-net#528] opened 2018-11-19 23:02 UTC
Could you please update references to ADAL v4.4.0?

There are a lot of important issues fixed in ADAL v4.3.0 and v4.4.0.

Please check the link below:
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases

4.4.0:
-Improvements and fixes to the token cache

**The serialized token cache can now be shared by different applications**, therefore providing SSO if the same user signs-in in both applications
On .NET Core, the Token cache was shared by all instances of applications in memory. This is now fixed Fixes consistency issues for advanced token cache migration scenarios from ADAL v3.x to ADAL v4.x to MSAL v2.x
**Cache lookups were optimized**. Work done in conjunction with ADAL.iOS and MSAL.iOS native) PR
The ExtraQueryParameter environment variable is now read on ADAL for the .NET Core platform, as was already the case in the .NET Framework case ADAL issue #1362
A Client credential API which should not be used on Xamarin.iOS, Xamarin.Android and UWP is now marked as obsolete
PR

4.3.0:
**Fix for cross-thread exception** when setting the ownerWindow in PlatformParameters ADAL issue #1277
Ensure error codes are public MSAL issue
**Device code flow enabled for ADFS**

**Comment by hovsepm** [comment] 2018-11-20 00:18
@SIGAN our ADAL dependency comes from Authentication which is hosted in a different repository and is owned by a different team - https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SdkCommon/Auth/Az.Auth/Az.Authentication/Microsoft.Rest.ClientRuntime.Azure.Authentication.csproj#L39 . Please reopen your ADAL 4.0 upgrade request in that [repository](https://github.com/Azure/azure-sdk-for-net/issues). Once that library will be upgraded we can also use it.

**Comment by hovsepm** [comment] 2018-11-20 00:19
Closed as By Design. Unfortunately we cannot upgrade Fluent SDK only. The upgrade should be done in Microsoft.Rest.ClientRuntime.Azure.Authentication nuget package.

**Closed** 2018-11-20 00:18 UTC
