### ISSUE TITLE
[BUG]IReadOnlyList<ISqlDatabase> ListBySqlServer returns null Tags

### ISSUE THREAD

**Issue by leeenglestone** [Azure/azure-libraries-for-net#747] opened 2019-07-24 14:44 UTC
**Describe the bug**
The sqlserver objects returned in `IReadOnlyList<Microsoft.Azure.Management.Sql.Fluent.ISqlDatabase> ListBySqlServer`
have a Tags property that is always null.

The databases in question have tags on them which I can see in Azure Portal

**To Reproduce**
Obtain an instance of the SqlServer, request a list of databases on it. See code snippet.

***Code Snippet***
```
var databases = azure.SqlServers.Databases.ListBySqlServer(sqlServer);

foreach(var database in databases)
{
   tags = database.Tags;
   // tags is null
}
```

**Expected behavior**
sqlServerDatabase.Tags should not be null

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : VS2019
 - Version of the Library used : 
Microsoft.Azure.Management.ResourceManager.Fluent v1.24.0

**Additional context**
All of the other Resources I have encountered are successfully returning Tags including StorageAccounts, Websites etc

**Comment by maggiepint** [comment] 2019-07-26 23:19
Thanks for the feedback. I have routed to the appropriate team for follow up.

**Comment by weidongxu-microsoft** [comment] 2019-12-05 03:59
https://github.com/Azure/azure-libraries-for-net/issues/563

**Comment by jeroenterheerdt** [comment] 2019-12-06 19:33
@weidongxu-microsoft can we close this now that there is a workaround in #563?

**Comment by weidongxu-microsoft** [comment] 2019-12-07 02:16
@jeroenterheerdt Basically yes, this should be a duplicate of https://github.com/Azure/azure-libraries-for-net/issues/563.

@leeenglestone Is it OK for you that we use https://github.com/Azure/azure-libraries-for-net/issues/563 to track this issue?

Also note that the fix on root cause is tracked at present via https://github.com/Azure/azure-libraries-for-java/issues/878 (update to composite-v3, on which version service fixed this). This is JAVA Fluent but the task is parallel for .NET Fluent.

**Comment by jaredmoo** [comment] 2019-12-09 05:13
From SQL side, this was fixed long ago with Server api-version 2015-05-01-preview. Fluent needs to be regenerated from package-composite-v1 or later.

**Comment by jeroenterheerdt** [comment] 2019-12-09 18:29
closing this issue here since it is tracked in #563

**Closed by jeroenterheerdt** 2019-12-09 18:29 UTC
Labels: Mgmt, SQL, customer-reported
