### ISSUE TITLE
Unable to compile UWP store app using fluent libraries

### ISSUE THREAD

**Issue by JoelMendoza** [Azure/azure-libraries-for-net#697] opened 2019-06-11 23:37 UTC
**Describe the bug**

A UWP project incorporating the following NuGet packages:
- DocumentFormat.OpenXml (version 2.9.1)
- Microsoft.Azure.Management.Fluent (version 1.22.2)
- Microsoft.NETCore.UniversalWindowsPlatform (version 6.2.8)

Fails to build in Release config if the build is set to use the .Net native toolchain (required for Store submission).

***Exception or Stack Trace***

This is the output:
```
8>C:\Users\joelm\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): warning :       MCG : warning MCG0007: Unresolved P/Invoke method 'libc!sysctl' for method 'System.Int32 Microsoft.DotNet.PlatformAbstractions.Native.NativeMethods.Darwin.sysctl(System.Int32*, System.UInt32, System.Byte*, System.UInt32*, System.IntPtr, System.UInt32)'. Calling this method would throw exception at runtime. Please make sure the P/Invoke either points to a Windows API allowed in UWP applications, or a native DLL that is part of the package. If for some reason your P/Invoke does not satisfy those requirements, please use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP APIs.
8>C:\Users\joelm\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): warning :       MCG : warning MCG0007: Unresolved P/Invoke method 'ntdll!RtlGetVersion' for method 'System.Int32 Microsoft.DotNet.PlatformAbstractions.Native.NativeMethods.Windows.RtlGetVersion(Microsoft.DotNet.PlatformAbstractions.Native.NativeMethods.Windows.RTL_OSVERSIONINFOEX)'. Calling this method would throw exception at runtime. Please make sure the P/Invoke either points to a Windows API allowed in UWP applications, or a native DLL that is part of the package. If for some reason your P/Invoke does not satisfy those requirements, please use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP APIs.
8>C:\Users\joelm\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): warning :       MCG : warning MCG0007: Unresolved P/Invoke method 'ntdll!RtlGetVersion' for method 'System.Int32 Microsoft.Azure.Documents.NativeMethods.Windows.RtlGetVersion(Microsoft.Azure.Documents.NativeMethods.Windows.RTL_OSVERSIONINFOEX)'. Calling this method would throw exception at runtime. Please make sure the P/Invoke either points to a Windows API allowed in UWP applications, or a native DLL that is part of the package. If for some reason your P/Invoke does not satisfy those requirements, please use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP APIs.
8>C:\Users\joelm\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): warning :       MCG : warning MCG0007: Unresolved P/Invoke method 'libc!sysctl' for method 'System.Int32 Microsoft.Azure.Documents.NativeMethods.Darwin.sysctl(System.Int32*, System.UInt32, System.Byte*, System.UInt32*, System.IntPtr, System.UInt32)'. Calling this method would throw exception at runtime. Please make sure the P/Invoke either points to a Windows API allowed in UWP applications, or a native DLL that is part of the package. If for some reason your P/Invoke does not satisfy those requirements, please use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP APIs.
8>    Generating code...
8>    Interop code generated.
8>  Generating serialization code
8>  Compiling interop code
8>  Generating System.Reflection.DispatchProxy proxy code.
8>  Cleaning up unreferenced code
8>  Generating native code
8>C:\Users\joelm\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): error : Error: NUTC301D:Internal Compiler Error: Invalid class variable '0' in signature while compiling method 'instance System.Boolean Microsoft.Azure.Management.AppService.Fluent.AppServiceCertificateImpl.Valid()'.
8>C:\Users\joelm\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): error : ILT0005: 'C:\Users\joelm\.nuget\packages\runtime.win10-x64.microsoft.net.native.compiler\2.1.8\tools\x64\ilc\Tools\nutc_driver.exe @"C:\Projects\Intact\PowerLine.CodeSolve\Solutions\ReAccess\Intact.PowerLine.ReAccess\obj\x64\Release\ilc\intermediate\MDIL\ReAccess.rsp"' returned exit code 1
10>Intact.PowerLine.ReAccess.Tests.Web -> C:\Projects\Intact\PowerLine.CodeSolve\Solutions\ReAccess\Intact.PowerLine.ReAccess.Tests.Web\bin\Release\netcoreapp2.2\Intact.PowerLine.ReAccess.Tests.Web.dll
10>Done building project "Intact.PowerLine.ReAccess.Tests.Web.csproj".
========== Rebuild All: 9 succeeded, 1 failed, 0 skipped ==========
```

**To Reproduce**

Create a new UWP project, add the Nuget projects noted in the Description section and build in Release config (make sure "Compile with .Net tool chain" is checked)

***Code Snippet***

N/A - no code needed to reproduce this error

**Expected behavior**

Successful build.

**Setup (please complete the following information):**
 - OS:  Windows 10 1809
 - IDE:  Visual Studio 2019
 - Framework:  UWP
 - NuGet Packages:
   - DocumentFormat.OpenXml (version 2.9.1)
   - Microsoft.Azure.Management.Fluent (version 1.22.2)
   - Microsoft.NETCore.UniversalWindowsPlatform (version 6.2.8)

**Additional context**

A UWP project will build in release with only the OpenXml package and will build in release with only the Azure.Management.Fluent package. **The build fails when both packages are included.**   Since this involves another package (OpenXml), I have opened an issue on the project's page:  [Open-Xml-SDK 595](https://github.com/OfficeDev/Open-XML-SDK/issues/595)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kurtzeborn** [comment] 2019-06-12 22:19
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by JoelMendoza** [comment] 2019-06-14 12:08
Thank you, I would really appreciate any assistance with this issue.

**Comment by Joel-Intact** [comment] 2019-07-02 15:24
@kurtzeborn - is there any update on this issue or is there workaround that I can implement?

**Comment by Joel-Intact** [comment] 2019-07-15 12:49
If it helps, I have attached the Diagnostic output of the Release build.  This is blocking us from deploying our product to the Windows Store and we would really appreciate assistance with this issue.

[Output of Diagnostic Build.txt](https://github.com/Azure/azure-libraries-for-net/files/3392325/Output.of.Diagnostic.Build.txt)

**Comment by yaohaizh** [comment] 2019-07-25 05:36
@Joel-Intact, from the diagnostic build output, there is no compilation errors related to Fluent as your original reported. What the latest situation here?

**Comment by Joel-Intact** [comment] 2019-07-25 16:36
Hi @yaohaizh, thank you for responding.  Originally, I titled the issue as ".NET Native compilation",  @kurtzeborn, changed the title to "Unable to compile UWP store app using fluent libraries", I'm guessing he had some insight on the issue and renamed it accordingly.

Since this issue does not involve any code, the explanation on that link does not apply.  It is actually very easy to reproduce this issue, it only involves 3 Microsoft NuGet Packages and building in release mode with the .net native tool chain.

I have followed the ILC Repro instructions and shared with file with the email:  dotnetnative@microsoft.com.  And I've also shared with them this issue.  Thanks again for following up and hopefully we can get this issue to the right team to have a quick resolution.

**Comment by yaohaizh** [comment] 2019-08-20 05:44
@Joel-Intact  Does this issue still persist? I might close this issue since fluent is not the root cause of this issue.

**Comment by Joel-Intact** [comment] 2019-08-20 12:43
@yaohaizh, this issue can be closed.  I was able to get my UWP project to build in release with the "Compile with .Net tool chain" checked.  The solution was to add these fluent related [run time directives](https://docs.microsoft.com/en-us/dotnet/framework/net-native/runtime-directives-rd-xml-configuration-file-reference) in the Default.rd.xml file:

```
<Assembly Name="Microsoft.Azure.Management.Compute.Fluent" Dynamic="Excluded" />
<Assembly Name="Microsoft.Azure.Management.ContainerInstance.Fluent" Dynamic="Excluded" />
<Assembly Name="Microsoft.Azure.Management.ContainerRegistry.Fluent" Dynamic="Excluded" />
<Assembly Name="Microsoft.Azure.Management.ContainerService.Fluent" Dynamic="Excluded" />
<Assembly Name="Microsoft.Azure.Management.CosmosDB.Fluent" Dynamic="Excluded" />
<Assembly Name="Microsoft.Azure.Management.Dns.Fluent" Dynamic="Excluded" />
<Assembly Name="Microsoft.Azure.Management.EventHub.Fluent" Dynamic="Excluded" />
<Assembly Name="Microsoft.Azure.Management.Fluent" Dynamic="Excluded" />
<Assembly Name="Microsoft.Azure.Management.Graph.RBAC.Fluent" Dynamic="Excluded" />
<Assembly Name="Microsoft.Azure.Management.KeyVault.Fluent" Dynamic="Excluded" />
<Assembly Name="Microsoft.Azure.Management.Locks.Fluent" Dynamic="Excluded" />
<Assembly Name="Microsoft.Azure.Management.Monitor.Fluent" Dynamic="Excluded" />
<Assembly Name="Microsoft.Azure.Management.Msi.Fluent" Dynamic="Excluded" />
<Assembly Name="Microsoft.Azure.Management.Network.Fluent" Dynamic="Excluded" />
<Assembly Name="Microsoft.Azure.Management.Redis.Fluent" Dynamic="Excluded" />
<Assembly Name="Microsoft.Azure.Management.ResourceManager.Fluent" Dynamic="Excluded" />
<Assembly Name="Microsoft.Azure.Management.Search.Fluent" Dynamic="Excluded" />
<Assembly Name="Microsoft.Azure.Management.ServiceBus.Fluent" Dynamic="Excluded" />
<Assembly Name="Microsoft.Azure.Management.Sql.Fluent" Dynamic="Excluded" />
<Assembly Name="Microsoft.Azure.Management.Storage.Fluent" Dynamic="Excluded" />
<Assembly Name="Microsoft.Azure.Management.TrafficManager.Fluent" Dynamic="Excluded" />
```
I still have an issue related with another library (Microsoft.Azure.DocumentDB.Core) and I'm trying to engage that team in a different github issue.

Thanks!

**Comment by yaohaizh** [comment] 2020-01-10 02:14
Thanks.

**Closed by yaohaizh** 2020-01-10 02:14 UTC
Labels: Mgmt, customer-reported
