### ISSUE TITLE
Exception when calling WebApps.ListAsync in Azure Function

### ISSUE THREAD

**Issue by bjornsallarp** [Azure/azure-libraries-for-net#191] opened 2018-03-01 11:11 UTC
I have a class library project in my solution that call the following method
`var webApps = await azure.WebApps.ListAsync();`
Target is .NET 4.7 and I use Newtonsoft 11.0.1

When I run the code from a Console App in the same solution, it works fine. When I run it from my Azure Function (.NET 4.7 target, Newtonsoft 11.0.1) project it throws an exception. This is the output in my Function window:

mscorlib: Exception while executing function: ExtractApps. Microsoft.Azure.Management.AppService.Fluent: Unable to deserialize the response. Newtonsoft.Json: Error reading JObject from JsonReader. Current JsonReader item is not an object: Null. Path 'properties.snapshotInfo', line 1, position 2727.

**Comment by hovsepm** [comment] 2018-03-01 18:46
@bjornsallarp could you post here server response?

**Comment by bjornsallarp** [comment] 2018-03-01 19:29
I prefer not posting the response here as it could disclose sensitive contractor information. I did set up a small sample that reproduce the problem here https://github.com/bjornsallarp/AzureFluentInFunctionException

Please let me know if I can provide you with the response in a private way. I could also provide you with our tennantid, clientid and a secret if it doesn't reproduce with other subscriptions.

**Comment by hovsepm** [comment] 2018-03-01 20:48
@bjornsallarp thanks for the repro.  could you send the payload to me directly to [me](mailto:hovsepm@microsoft.com)?

**Comment by hovsepm** [comment] 2018-04-16 18:02
@bjornsallarp thank you for finding the root cause. The issue exists only in V1 of Azure Functions. The working solution for now would be to migrate your project to V2 of Azure Functions (i.e. .Net Core version which is currently in beta).

**Comment by hovsepm** [comment] 2018-04-16 18:03
The issue is not in the Newtonsoft.Json but in Microsoft.Rest.ClientRuntime library in Azure Functions V1 and affects all the Azure management libraries generated by Autorest. The thing is that Azure Functions V1 during runtime loads Microsoft.Rest.ClientRuntime v2.3.3.0 which contains a deserialization bug that was fixed in v3.3.4 according to github issue https://github.com/Azure/azure-sdk-for-net/issues/2501 .

**Comment by shilsmarty** [comment] 2018-04-27 00:07
i think this issue still persist.

"The thing is that Azure Functions V1 during runtime loads Microsoft.Rest.ClientRuntime v2.3.3.0 which contains a deserialization bug that was fixed in v2.3.4 according to github issue Azure/azure-sdk-for-net#2501 ."

Am using Microsoft.Rest.ClientRuntime version v2.3.10 but still same error as above.

**Comment by hovsepm** [comment] 2018-05-15 21:48
Fix in Azure Functions V1 was updated and deployed with the last 1.0 release (1.0.11702). 
Please open a new issue and provide detailed information on region and Azure Functions runtime version if you will still hit this.

**Closed by hovsepm** 2018-05-15 21:48 UTC
