### ISSUE TITLE
Failed to encrypt VM

### ISSUE THREAD

**Issue by manish1604** [Azure/azure-libraries-for-net#538] opened 2018-12-01 00:53 UTC
IVirtualMachine.DiskEncryption.EnableAsync(keyVaultId, aadClientId, aadClientSecret
is failing to encrypt the virtual machine disks.

Error stack trace:

Long running operation failed with status 'Failed'. Additional Info:'VM has reported a failure when processing extension 'AzureDiskEncryption'. Error message: "Failed to configure bitlocker as expected. Exception: ProtectKeyWithExternalKey failed with 2147942450, InnerException: , stack trace:    at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerWmi.Win32EncryptableVolumeWrap.ProtectKeyWithExternalkey()
   at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerOperations.GenerateKeyForVolume(EncryptableVolume vol)
   at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.GenerateAndUploadProtectorForVolume(EncryptableVolume vol, Boolean saveKeyToBekVolume)
   at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.GenerateAndUploadDataVolumeProtectors()
   at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.EnableEncryption()
   at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.HandleEncryptionOperations()
   at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.OnEnable()".'

Note: 
1. The same virtual machine can be encrypted successfully using powershell (Set-AzureRmVMDiskEncryptionExtension)
2. When I check the status of the disk from portal, it shows as encrypted.

**Comment by yaohaizh** [comment] 2019-10-12 03:17
@ChenTanyi, when you implement the feature of NoAAD, please investigate this issue for your convenient. 

Thanks.

**Comment by ChenTanyi** [comment] 2019-10-15 07:28
Hi @manish1604, I have tried with Fluent(v1.17.0) but I cannot reproduce this issue.

For the exception, it is caused by BitLocker from service side. I think it may be the service problem at the time. Since there is long time from this issue, I hope you are not in trouble with it now.

If you still have trouble about it, could you please show the whole code snippet about your VM and KeyVault?

We will close this issue if there is no reply at the end of this sprint.

Thanks.

The following is my code snippet which cannot reproduce.
```csharp
            azure.ResourceGroups.Define("vmssdlrkj").WithRegion(Region.AsiaEast).Create();
            var vm = azure.VirtualMachines.Define("abc1")
                .WithRegion(Region.AsiaEast)
                .WithExistingResourceGroup("vmssdlrkj")
                .WithNewPrimaryNetwork("10.0.0.0/24")
                .WithPrimaryPrivateIPAddressDynamic()
                .WithNewPrimaryPublicIPAddress("sfslejrlsv")
                .WithPopularWindowsImage(KnownWindowsVirtualMachineImage.WindowsServer2008R2_SP1)
                .WithAdminUsername("abc")
                .WithAdminPassword("sldj159werSDFG@#$^$%")
                .WithSize(ContainerServiceVMSizeTypes.StandardE2sV3)
                .Create();

            var vault = azure.Vaults.Define("vltsklejlrks1")
                .WithRegion(Region.AsiaEast)
                .WithExistingResourceGroup("vmssdlrkj")
                .DefineAccessPolicy()
                    .ForServicePrincipal(credentials.ClientId)
                    .AllowCertificateAllPermissions()
                    .AllowKeyAllPermissions()
                    .AllowSecretAllPermissions()
                    .Attach()
                .WithDiskEncryptionEnabled()
                .Create();
            vm.DiskEncryption.Enable(vault.Id, credentials.ClientId, clientSecret);
```

**Comment by yaohaizh** [comment] 2019-10-24 05:06
This issue is not reproduced anymore, close it now. @manish1604 , feel free to re-open this issue if it still exists on your side.

**Closed by yaohaizh** 2019-10-24 05:06 UTC
