### ISSUE TITLE
Is is possible to export a SQL Database using the fluent API?

### ISSUE THREAD

**Issue by panesofglass** [Azure/azure-libraries-for-net#126] opened 2018-01-03 05:45 UTC
Is there an API for exporting a database to Azure Storage available in the fluent libraries?

**Comment by milismsft** [comment] 2018-01-03 16:24
Not at the moment; it's in the plan to add import/export functionality for the next release though.

**Comment by hovsepm** [comment] 2018-01-03 18:49
duplicate of https://github.com/Azure/azure-libraries-for-java/issues/112

**Closed by hovsepm** 2018-01-03 18:49 UTC
