### ISSUE TITLE
No Minimum TLS version through IWebApp interface

### ISSUE THREAD

**Issue by scottgerring** [Azure/azure-libraries-for-net#421] opened 2018-08-01 06:08 UTC
Looks like there's no way to specify a minimum TLS version via the `IWebApp` interface and a hardcoded default of 1.2 somewhere. As far as I can see, this makes it impossible to configure a web app that supports older versions of TLS without intervening via the Azure portal. 
Is there a workaround for this, or is there the possibility the interface could be exposed in the future?

**Comment by praries880** [comment] 2019-03-05 21:55
Closing this  as a duplicate of #556

**Closed by praries880** 2019-03-05 21:55 UTC
