### ISSUE TITLE
Does getting all resources of a type make an individual call for each Resource Group?

### ISSUE THREAD

**Issue by sai-manoj-kumar** [Azure/azure-libraries-for-net#251] opened 2018-04-07 08:33 UTC
This is more of a question/feature-request than a bug.

In the below method and similar others, to list all resources of a particular type, will it make different REST calls for each resource group?
If yes, Is it not a performance concern? Why can't we make a single call using filter API with resourceType filter across all resource groups in a subscription?

```
public IEnumerable<IVirtualNetworkGateway> List()
        {
            return Manager.ResourceManager.ResourceGroups.List()
                .SelectMany(rg => ListByResourceGroup(rg.Name));
}
```

**Comment by hovsepm** [comment] 2018-04-09 19:52
@sai-manoj-kumar your example with definitely do a separate call for each RG. Does ARM supports filtering by resourceType? If so this could be easily fixed on our side.

**Comment by sai-manoj-kumar** [comment] 2018-04-10 04:48
@hovsepm Yes, ARM does support that. I remember using it. Not able to find Microsoft docs link. 
But the below Stackoverflow answer also suffices, IMO.
[https://stackoverflow.com/a/34275750/1032479](https://stackoverflow.com/a/34275750/1032479)

**Comment by hovsepm** [comment] 2018-04-10 17:57
@sai-manoj-kumar thanks for the link. For now our support of Odata filters in Fluent SDK is very limited. But you can make a call through Inner and provide your filter string. In your case it should look like this (with full type names for your convenience) :
```
await Manager.ResourceManager.Inner.ResourceGroups.ListAsync(new Microsoft.Rest.Azure.OData.ODataQuery<Microsoft.Azure.Management.ResourceManager.Fluent.Models.ResourceGroupFilterInner>("your odata expression"))
```

**Comment by sai-manoj-kumar** [comment] 2018-04-12 17:40
@hovsepm It looks like the above call also makes at least one call per RG. Is there a way I can do it on Inner directly?

**Comment by hovsepm** [comment] 2018-04-12 23:39
@sai-manoj-kumar 
I think this one should do the trick:
```
await Manager.ResourceManager.GenericResources.Inner.ListAsync(new Microsoft.Rest.Azure.OData.ODataQuery<Microsoft.Azure.Management.ResourceManager.Fluent.Models.ResourceGroupFilterInner>("your odata expression"))
```

**Comment by hovsepm** [comment] 2018-04-12 23:40
but you will need to call ListNextAsync afterwards to get all the pages from server.

**Comment by hovsepm** [comment] 2018-04-12 23:45
I think we need to expose List method on GenericResource that will accept Odata filter string expression. Please upvote for prioritization.

**Comment by hovsepm** [comment] 2018-10-18 22:59
Closing as by design for current stage.

**Closed by hovsepm** 2018-10-18 22:59 UTC
